### ISSUE TITLE
Add support for machine-readable output

### ISSUE THREAD

**Issue by shabalind** [google/swift-benchmark#13]
Currently we only support human-readable tabular output. It's great for iterative development locally but it's hard to use from other scripts (i.e., for continuous performance tracking).

To fix this, we should add a JSON-based output format that contains information in the structured format.

**Comment by mattt** [comment]
The [original Google benchmark project](https://github.com/google/benchmark) offers some strong guidance for CSV and JSON output formats. [[1]] It'd make sense to support the same format, and command-line / ENV variable arguments.

[1]: https://github.com/google/benchmark#output-formats

**Comment by shabalind** [comment]
Hi @mattt, thanks a lot for the feedback, we'll try to make sure that the output format is close to the output of the original google/benchmark!
