### ISSUE TITLE
Add support for the output column customisation 

### ISSUE THREAD

**Issue by shabalind** [google/swift-benchmark#15]
Currently the output of the benchmark run looks like this:

```
$ swift run -c release BenchmarkMinimalExample
running add string no capacity
running add string reserved capacity

name                          time        std                   iterations  
--------------------------------------------------------------------------
add string no capacity        40053.0 ns  ± 1681.4582875216558  100000      
add string reserved capacity  39675.0 ns  ± 769.3813620184557   100000    
```

The columns are hardcoded to always be: time, std, iterations. It would be great to make it possible to customize this columns to only include what's desired. The end-user UI will include a new command-line option `--show`:

```
$ swift run -c release BenchmarkMinimalExample --show time,std
running add string no capacity
running add string reserved capacity

name                          time        std                   
--------------------------------------------------------------
add string no capacity        40053.0 ns  ± 1681.4582875216558  
add string reserved capacity  39675.0 ns  ± 769.3813620184557 
```

This will open the opportunity to add more column options to choose from such as min/max/avg/percentile values/etc.

**Comment by mattt** [comment]
As I mentioned in https://github.com/google/swift-benchmark/pull/34#issuecomment-633598625, this can be accomplished without adding any options to the benchmark command itself, by using `cut` with tab-separated columns:

```terminal
$ swift run -c release BenchmarkMinimalExample
running add string no capacity... done! (1936.30 ms)
running add string reserved capacity... done! (1872.81 ms)

name                        	time      	std       	iterations
----------------------------	----------	----------	----------
add string no capacity      	42033.0 ns	±  41.20 %	     31676
add string reserved capacity	40564.0 ns	±  25.78 %	     33226

$ swift run -c release BenchmarkMinimalExample | cut -f1 -f2 -f3
name                        	time      	std       
----------------------------	----------	----------
add string no capacity      	42033.0 ns	±  41.20 %
add string reserved capacity	40564.0 ns	±  25.78 %
```

**Comment by shabalind** [comment]
@mattt This would require for every possible metric to be printed by default, which will stop being practical once we include more metrics (including user-define metrics), and add more ways to summarize them (i.e., percentile N for every N).

**Comment by mattt** [comment]
@shabalind I think that depends on how we design command argument handling.

For example, the default 4 column output could remain standard, with the option to append additional fields:

```terminal
$ swift run -c release BenchmarkMinimalExample --include-n95
name                        	time      	std       	iterations	n95
----------------------------	----------	----------	----------	----------
add string no capacity      	42033.0 ns	±  41.20 %	     31676	50000.0 ns
```

Regardless of if or whether additional columns are supported, tab-delimited plain text tables generally are more useful than space-delimited, and I think they're worth consideration.

**Comment by shabalind** [comment]
@mattt More compact output is preferable, because it lets one fit more text on the screen within the same output column limit. I really think we should keep the old formatting for columns as the default for that reason.
