### ISSUE TITLE
Improve time formatting in console output

### ISSUE THREAD

**Issue by saeta** [google/swift-benchmark#26]
Currently, time is always in denominations of nanoseconds. This is fantastic for fast micro-benchmarks, but somewhat suboptimal for larger benchmarks (see example below). It'd be great to automatically pick a reasonable time unit for each benchmark (while simultaneously supporting a flag to use nanoseconds across all, which can make comparisons across benchmarks easier).

Related: https://github.com/google/swift-benchmark/issues/25

**Comment by saeta** [comment]
If someone would like to pick this up, check out [`PlainTextReporter.report(results:)`](https://github.com/google/swift-benchmark/blob/4c8bab04c6a0f9e09e4e091d831b146f77842ed9/Sources/Benchmark/BenchmarkReporter.swift#L40)

**Comment by mattt** [comment]
I started on a solution using Foundation's [`MeasurementFormatter`](https://developer.apple.com/documentation/foundation/measurementformatter), but I was disappointed to learn that its [`naturalScale`](https://developer.apple.com/documentation/foundation/measurementformatter/unitoptions/1642065-naturalscale) option is much less capable than advertised in the documentation. For example:

```swift
let formatter = MeasurementFormatter()
formatter.unitStyle = .short
formatter.unitOptions = .naturalScale

let measurement = Measurement<UnitDuration>(value: 1000000, unit: .nanoseconds)
formatter.string(from: measurement) // "0s" (expected "1ms")
```

There are other caveats that make this a less appealing option, including the `nanoseconds` unit being a new API in 10.15.

**Comment by shabalind** [comment]
A simpler solution would be to provide a `--time-unit <s/ms/us/ns>`, and let the user pick the best option for himself.
