### ISSUE TITLE
Add integration with XCTest 

### ISSUE THREAD

**Issue by shabalind** [google/swift-benchmark#31]
As suggested by @dabrahams, it would be good to have an integration with XCTest to run benchmarks as tests.

This would imply that we can create an XCTest test suite out of benchmark suite and run all benchmarks. Each benchmark will map to a single test case where the benchmark is run a single iteration.

**Comment by dabrahams** [comment]
This doesn't require anything really fancy.  Some small amount of boilerplate would be OK.

**Comment by shabalind** [comment]
Thanks for the suggestion, @dabrahams! 👍

**Comment by dabrahams** [comment]
Oh, @shabalind, I would be happy enough if there was just a single test case for all the benchmarks.  It's not like we're going to get useful error reports; this is just about having an automated way to ask "did I break anything" before pushing a change and having the answer consider the benchmarks.

**Comment by mattt** [comment]
@dabrahams Does this need to go through XCTest, or is the high-level goal to add CI coverage to the examples? If that's actually the case, I have branch on my fork that has CI passing with both the unit tests and the examples: https://github.com/mattt/swift-benchmark/pull/1

<img width="1090" alt="Screen Shot 2020-05-25 at 10 35 31" src="https://user-images.githubusercontent.com/7659/82833659-82234a80-9e73-11ea-983d-da2a3bc5315d.png">

The challenge with doing this through a conventional Swift Package Manager test target is that the example benchmark executables must be run in release mode. Compiling tests in release mode means that we can't use `@testable` import. Even if we create a separate test target and `--filter` the `swift test -c release` invocation on it, that still wouldn't work, as `swift test` builds all test target modules.

**Comment by dabrahams** [comment]
@mattt it needs to be that a single simple command from the command-line will test all the code and make sure the benchmarks build/run.  I don't care too much what that command is, but I think as long as we are exposing SPM Packages we should make `swift test` do this.  
It's easy enough to set flags to build any test in the equivalent of release mode... but why can't we build and run debug benchmark executables?

**Comment by mattt** [comment]
> It's easy enough to set flags to build any test in the equivalent of release mode... but why can't we build and run debug benchmark executables?

You can, but all you get when you run them is a message telling you to build and run with a release configuration.

**Comment by dabrahams** [comment]
Aren't we in 100% control of what happens when these executables are run?

It's still way better than nothing, as it makes sure the benchmarks still compile.

**Comment by mattt** [comment]
> Aren't we in 100% control of what happens when these executables are run?

Of course. But changing these example benchmarks to run normally in debug mode would entail the same for all other benchmark executables, unless we either make this behavior configurable or special-case these, specifically. 

It's the same kind of problem you run into with testability of libraries. Unfortunately, I don't see a way to smoke test these example benchmarks with a single `swift test` invocation.
 
> It's still way better than nothing, as it makes sure the benchmarks still compile.

My proposed [branch](https://github.com/mattt/swift-benchmark/pull/1) would ensure this on the CI level.

If you wanted to do this with a single command locally, maybe there's a way to do that with CMake?

**Comment by dabrahams** [comment]
@mattt I don't see what the problem is.  I haven't looked at the code of this library, but it sees to me  there must be lots of ways we could make this work for all executables built with this library, including checking environment variables or arguments passed on the command line.  As  for CMake, @compnerd and I spent a few hours last week trying to make it so I could do a CMake build and ran out of time.  Also, this library still needs to work for non-CMake projects.
