### ISSUE TITLE
Automatically detect a reasonable number of iterations

### ISSUE THREAD

**Issue by shabalind** [google/swift-benchmark#8]
Currently the framework doesn't make any attempt at understanding how long does a single benchmark iteration run. The number of benchmark is hardcoded to a static constant, which is the same for all benchmarks. Given that some benchmarks can take way longer than the others, this causes uneven amount of time spent per benchmark.

**Comment by saeta** [comment]
Per @shabalind in https://github.com/google/swift-benchmark/pull/7#issuecomment-626798803 we should probably look to https://github.com/google/benchmark/blob/master/src/benchmark_runner.cc#L252 for inspiration.
