### ISSUE TITLE
Suggestion: consistent time formatting?

### ISSUE THREAD

**Issue by stephencelis** [google/swift-benchmark#82]
swift-benchmark currently strips `.0` when printing the time column:

https://github.com/google/swift-benchmark/blob/9d4782b2f616d2b97bf302ba6aa8aff4f8283983/Sources/Benchmark/BenchmarkFormatter.swift#L22-L23

This means when several benchmarks are printed in a run, they may be printed inconsistently over the column:

```
name                                        time        std        iterations
-----------------------------------------------------------------------------
String.removeFirst()                        81679174 ns ±   1.64 %         16
String.removeFirst(1)                       81369569 ns ±   2.42 %         17
Substring.removeFirst()                      132.500 ns ± 274.18 %    1000000
Substring.removeFirst(1)                    93850715 ns ±   2.25 %         15
```

In this example `Substring.removeFirst()` has a trailing `.500` that makes it difficult to see just how much faster it is when viewing at-a-glance. (I'm not sure if these occasional sub-nanosecond measurements point to a bug elsewhere.) Any chance this formatting could be made more consistent for legibility?

**Comment by stephencelis** [comment]
Oh ha, should have performed a search. Just saw this: https://github.com/google/swift-benchmark/pull/81

**Comment by regexident** [comment]
Beat you to it by mere hours, hah! 😁
